### ISSUE TITLE
Doesn't work on Expo SDK 52 

### ISSUE THREAD

**Issue by JRS-Developer** [FormidableLabs/react-native-ama#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Bug report

```markdown
I upgraded to expo 52 and it shows me this error when trying to run: `expo run:android`


> Task :react-native-ama:compileDebugKotlin FAILED
e: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/react-native-ama/android/src/main/java/com/reactnativeama/components/AmaFlatListWrapperManager.kt:29:3 'addView' overrides nothing
```

All Logs
```
❯ yarn run android
yarn run v1.22.22
$ EXPO_UNSTABLE_ATLAS=true expo run:android
env: load .env.local
env: export EXPO_PUBLIC_API_URL EXPO_PUBLIC_EXTERNAL_IMAGE_HOSTNAME EXPO_PUBLIC_RECAPTCHA_SITE_KEY EXPO_PUBLIC_RECAPTCHA_DOMAIN EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID EXPO_PUBLIC_PAYPAL_CLIENT_ID EXPO_PUBLIC_PAYPAL_MODE SENTRY_AUTH_TOKEN GOOGLE_IOS_URL_SCHEME NGROK_APP_LINK_DOMAIN
› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
 ℹ️I  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@5.0.16)

> Configure project :expo

Using expo modules
  - expo-asset (11.0.1)
  - expo-clipboard (7.0.0)
  - expo-constants (17.0.3)
  - expo-crypto (14.0.1)
  - expo-dev-client (5.0.4)
  - expo-dev-launcher (5.0.16)
  - expo-dev-menu (6.0.11)
  - expo-document-picker (13.0.1)
  - expo-file-system (18.0.4)
  - expo-font (13.0.1)
  - expo-image (2.0.2)
  - expo-image-loader (5.0.0)
  - expo-image-picker (16.0.3)
  - expo-json-utils (0.14.0)
  - expo-keep-awake (14.0.1)
  - expo-linear-gradient (14.0.1)
  - expo-linking (7.0.3)
  - expo-manifests (0.15.4)
  - expo-modules-core (2.0.6)
  - expo-secure-store (14.0.0)
  - expo-splash-screen (0.29.13)
  - expo-system-ui (4.0.4)
  - expo-web-browser (14.0.1)


> Configure project :react-native-reanimated
Android gradle plugin: 8.6.0
Gradle: 8.10.2

> Task :expo-manifests:compileDebugKotlin
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/EmbeddedManifest.kt:19:16 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/EmbeddedManifest.kt:19:86 'getLegacyID(): String' is deprecated. Prefer scopeKey or projectId depending on use case
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/ExpoUpdatesManifest.kt:16:16 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-manifests/android/src/main/java/expo/modules/manifests/core/Manifest.kt:15:12 'getRawJson(): JSONObject' is deprecated. Prefer to use specific field getters

> Task :react-native-ama:compileDebugKotlin FAILED
e: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/react-native-ama/android/src/main/java/com/reactnativeama/components/AmaFlatListWrapperManager.kt:29:3 'addView' overrides nothing

> Task :react-native-fast-shadow:compileDebugJavaWithJavac
Note: /home/jose/Trabajo/onlylatest/mobile/node_modules/react-native-fast-shadow/android/src/main/java/com/reactnativefastshadow/ShadowFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :expo-web-browser:compileDebugKotlin
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-web-browser/android/src/main/java/expo/modules/webbrowser/WebBrowserModule.kt:112:15 'setToolbarColor(Int): CustomTabsIntent.Builder' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-web-browser/android/src/main/java/expo/modules/webbrowser/WebBrowserModule.kt:117:15 'setSecondaryToolbarColor(Int): CustomTabsIntent.Builder' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-web-browser/android/src/main/java/expo/modules/webbrowser/WebBrowserModule.kt:123:15 'addDefaultShareMenuItem(): CustomTabsIntent.Builder' is deprecated. Deprecated in Java

> Task :expo-image-picker:compileDebugKotlin
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt:123:23 'TAG_ISO_SPEED_RATINGS: String' is deprecated. Deprecated in Java

> Task :expo-secure-store:compileDebugKotlin
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.kt:5:27 'PreferenceManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.kt:110:9 Variable 'legacyReadFailedWarning' is never used
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.kt:247:23 'PreferenceManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.kt:247:41 'getDefaultSharedPreferences(Context!): SharedPreferences!' is deprecated. Deprecated in Java

> Task :expo-dev-menu:compileDebugKotlin
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/debug/java/expo/modules/devmenu/DevMenuManager.kt:18:38 'ReactFontManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/debug/java/expo/modules/devmenu/DevMenuManager.kt:205:7 'ReactFontManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/debug/java/expo/modules/devmenu/DevMenuManager.kt:429:43 The corresponding parameter in the supertype 'DevMenuManagerInterface' is named 'shouldAutoLaunch'. This may cause problems when calling this function with named arguments.
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/com/facebook/react/devsupport/DevMenuSettingsBase.kt:6:27 'PreferenceManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/com/facebook/react/devsupport/DevMenuSettingsBase.kt:18:51 'PreferenceManager' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/com/facebook/react/devsupport/DevMenuSettingsBase.kt:18:69 'getDefaultSharedPreferences(Context!): SharedPreferences!' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/com/facebook/react/devsupport/DevMenuSettingsBase.kt:56:16 This declaration overrides deprecated member but not marked as deprecated itself. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/expo/modules/devmenu/fab/MovableFloatingActionButton.kt:173:17 'computeBounds(RectF, Boolean): Unit' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/main/java/expo/modules/devmenu/helpers/DevMenuOkHttpExtension.kt:58:19 'create(MediaType?, String): RequestBody' is deprecated. Moved to extension function. Put the 'content' argument first to fix Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/android/src/react-native-74/main/expo/modules/devmenu/react/DevMenuPackagerConnectionSettings.kt:16:9 Parameter 'host' is never used
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/vendored/react-native-safe-area-context/android/devmenu/com/th3rdwave/safeareacontext/SafeAreaProviderManager.kt:5:34 'MapBuilder' is deprecated. Deprecated in Java
w: file:///home/jose/Trabajo/onlylatest/mobile/node_modules/expo-dev-menu/vendored/react-native-safe-area-context/android/devmenu/com/th3rdwave/safeareacontext/SafeAreaProviderManager.kt:29:14 'MapBuilder' is deprecated. Deprecated in Java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ama:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 27s
575 actionable tasks: 147 executed, 413 from cache, 15 up-to-date
Error: /home/jose/Trabajo/onlylatest/mobile/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86_64,arm64-v8a exited with non-zero code: 1
Error: /home/jose/Trabajo/onlylatest/mobile/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86_64,arm64-v8a exited with non-zero code: 1
    at ChildProcess.completionListener (/home/jose/Trabajo/onlylatest/mobile/node_modules/@expo/spawn-async/src/spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/home/jose/Trabajo/onlylatest/mobile/node_modules/@expo/spawn-async/src/spawnAsync.ts:28:21)
    at spawnGradleAsync (/home/jose/Trabajo/onlylatest/mobile/node_modules/@expo/cli/src/start/platforms/android/gradle.ts:134:28)
    at assembleAsync (/home/jose/Trabajo/onlylatest/mobile/node_modules/@expo/cli/src/start/platforms/android/gradle.ts:83:16)
    at runAndroidAsync (/home/jose/Trabajo/onlylatest/mobile/node_modules/@expo/cli/src/run/android/runAndroidAsync.ts:48:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by zibs** [comment]
Hey @JRS-Developer If you're moving to the new architecture, you'll need to start using 1.0 of this package and above. This library removed all it's native code in the latest release.
